### ISSUE TITLE
benchmarks pyro-nn

### ISSUE THREAD

**Issue by mhubii** [matteo-ronchetti/torch-radon#12]
are there any plans to benchmark it against [pyro-nn](https://github.com/csyben/PYRO-NN)

**Comment by matteo-ronchetti** [comment]
I think it would be interesting to compare the speed of the two libraries but I tried installing pyro-nn and got the following error `Could not find a version that satisfies the requirement pyronn-layers>=0.1.0`.
There is an [issue](https://github.com/csyben/PYRO-NN/issues/12) in the pyro-nn repo which reports the same error and which has been open for more than one year without any reply.
Until I can find how to install the library I'm unable to benchmark it.

**Comment by csyben** [comment]
That would be a nice idea.
@matteo-ronchetti could you give me some information about the used system ? The installation error appears in some cases with incompatible versions, i try to track it down currenty.

**Comment by matteo-ronchetti** [comment]
I'm using Linux, Python 3.7.7 and have installed Tensorflow 2.3.1

**Comment by csyben** [comment]
I think there is an error in the python packaging leading to a failed version check when python 3.7 or 3.8 is used. I am currently looking into the problem, until a new package is realsed I assume going with python 3.6 should fix the issue. Sorry for the inconvinience.

**Comment by csyben** [comment]
I updated the pyronn-layer package. Should work now for python3.6, 3.7 and 3,8.

best

**Comment by matteo-ronchetti** [comment]
Thanks, I still have problems with CUDA version. Can you please create a docker container with pyronn installed? I think it would be the easiest way for me and others to use the library

**Comment by csyben** [comment]
You can use the Docker containers provided by Tensorflow [1]. They are setup accordingliy, and PYRO-NN can be installed there without problems. You can either use the _latest_ container, or the container for custom-ops (which I use to build the packages).

best.

[1] https://www.tensorflow.org/install/docker

**Comment by matteo-ronchetti** [comment]
OK I was able to install pyronn using docker and to benchmark it. The benchmark code is available here. In the next few days I will write similar code to benchmark TorchRadon in the same setting.

These are current FPS obtained with Pyronn on my GPU:
Parallel Forward:  433FPS
Parallel Backward: 2090FPS
Fanbeam Forward: 401FPS
Fanbeam Backwars: 970FPS

TorchRadon seems to be from 9 to 50 times faster than pyronn

**Comment by yizhilanmaodhh** [comment]
error: command 'gcc' failed with exit status 1，I ran into this error when I install it. Has anyone encountered it? How to solve it?
